version: '3.9'  # use version 3.9 or any compatible version
services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.15  # Specify the version of etcd you need
    container_name: etcd
    ports:
      - "2379:2379"  # client communication
      - "2380:2380"  # server-to-server communication
    command:
      - /usr/local/bin/etcd
      - --name=etcdnode
      - --advertise-client-urls=http://0.0.0.0:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://0.0.0.0:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcdnode=http://0.0.0.0:2380
      - --initial-cluster-token=etcd-cluster-1
      - --initial-cluster-state=new
