# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hooke.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhooke.proto\x12\x05hooke\":\n\x0cNeighborInfo\x12\x14\n\x0cnext_node_id\x18\x01 \x01(\t\x12\x14\n\x0cprev_node_id\x18\x02 \x01(\t\"7\n\x08NodeInfo\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x0f\n\x07node_id\x18\x03 \x01(\t\"\x06\n\x04Void2n\n\x0b\x43oordinator\x12\x32\n\x08NodeJoin\x12\x0f.hooke.NodeInfo\x1a\x13.hooke.NeighborInfo\"\x00\x12+\n\tNodeLeave\x12\x0f.hooke.NodeInfo\x1a\x0b.hooke.Void\"\x00\x32?\n\x04Node\x12\x37\n\x11MembershipChanges\x12\x13.hooke.NeighborInfo\x1a\x0b.hooke.Void\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hooke_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NEIGHBORINFO']._serialized_start=22
  _globals['_NEIGHBORINFO']._serialized_end=80
  _globals['_NODEINFO']._serialized_start=82
  _globals['_NODEINFO']._serialized_end=137
  _globals['_VOID']._serialized_start=139
  _globals['_VOID']._serialized_end=145
  _globals['_COORDINATOR']._serialized_start=147
  _globals['_COORDINATOR']._serialized_end=257
  _globals['_NODE']._serialized_start=259
  _globals['_NODE']._serialized_end=322
# @@protoc_insertion_point(module_scope)
